spring:
  application:
    name: bookflow

  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000