spring:
  config:
    import: optional:file:.env.test[.properties]

  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    root: WARN
    com.clover: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 1000
  refresh-token-expiration-ms: 5000

aladin:
  ttbkey: ${ALADIN_TTBKEY}

nl:
  key: ${NL_KEY}